-- ═══════════════════════════════════════════════════
-- MIGRATION: CLIENT CREDIT (ardoises / accounts receivable)
-- Run in the Neon SQL Editor. Additive and safe to re-run.
--
-- ── WHY THIS EXISTS ───────────────────────────────────────────────────
-- Until now an ardoise lived ONLY in one till's localStorage key
-- 'servio-credits-v1'. No table, no endpoint, no sync. If that machine died,
-- was stolen, or had its browser data cleared, the record of who owes money was
-- gone — and the owner could never see it from the web. For a café running
-- ardoises this is usually the most valuable list in the business.
--
-- ── OWNERSHIP (see ARCHITECTURE.md §2) ────────────────────────────────
-- The EXE owns credit: an ardoise is opened, charged and settled at the counter.
-- The web READS it. The web may never invent a credit sale, exactly as it may
-- never invent a stock sale.
--
-- ── TWO TABLES, MIRRORING THE STOCK DESIGN (§6) ───────────────────────
--   credits            → current balance per client (a CACHE, pushed by the POS)
--   credit_movements    → append-only history, the auditable truth
-- Keeping both lets the web detect drift between what the till says a client
-- owes and what the movements add up to. A mismatch is worth investigating.
--
-- ACCOUNTING RULE the movements encode (§3): a credit sale increases the debt
-- and counts as revenue on the day of the sale; a repayment decreases the debt
-- and is a cash pay-in, NEVER a second sale. Otherwise the same money is counted
-- twice in revenue.
-- ═══════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS credits (
  id             BIGSERIAL     PRIMARY KEY,
  restaurant_id  INTEGER       NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,

  -- Stable per-client key generated by the POS. The POS previously identified a
  -- client only by array position, which cannot survive a sync, so new clients
  -- carry a `cid` and older ones get a deterministic slug of their name.
  client_key     VARCHAR(64)   NOT NULL,

  name           VARCHAR(120)  NOT NULL,
  phone          VARCHAR(40)   DEFAULT '',

  -- What the till says is owed right now. Cache: the movements are the truth.
  balance        NUMERIC(12,3) NOT NULL DEFAULT 0,

  -- Set when the client is removed on the till. Kept rather than deleted: a
  -- deleted ardoise that still had a balance is itself a finding.
  archived       BOOLEAN       NOT NULL DEFAULT FALSE,
  archived_at    TIMESTAMPTZ,

  terminal_id    VARCHAR(64)   DEFAULT '',
  client_ts      TIMESTAMPTZ,                -- last change according to the till
  updated_at     TIMESTAMPTZ   DEFAULT NOW(),
  created_at     TIMESTAMPTZ   DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_credits_key
  ON credits(restaurant_id, client_key);

-- "Who owes me money", biggest debt first — the main report.
CREATE INDEX IF NOT EXISTS idx_credits_balance
  ON credits(restaurant_id, balance DESC)
  WHERE archived = FALSE;


CREATE TABLE IF NOT EXISTS credit_movements (
  id             BIGSERIAL     PRIMARY KEY,
  restaurant_id  INTEGER       NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  client_key     VARCHAR(64)   NOT NULL,

  --   'credit'  → goods taken on account. Debt UP.   (delta > 0)
  --   'payment' → client settled part or all.  Debt DOWN. (delta < 0)
  --   'adjust'  → manual correction, reason required.
  kind           VARCHAR(16)   NOT NULL,

  -- Signed change to the debt, so SUM(delta) is the balance.
  delta          NUMERIC(12,3) NOT NULL,

  -- How a repayment arrived. Only 'cash' puts money in the drawer, which is why
  -- the POS opens the drawer for cash settlements only.
  pay_method     VARCHAR(20)   DEFAULT '',

  -- Human-readable summary of the goods, for a credit sale.
  items_summary  VARCHAR(400)  DEFAULT '',
  sale_num       INTEGER,                    -- ticket number when it was a sale
  reason         VARCHAR(200)  DEFAULT '',

  actor          VARCHAR(80)   DEFAULT '',   -- who was logged in at the till
  session_id     VARCHAR(64)   DEFAULT '',
  terminal_id    VARCHAR(64)   DEFAULT '',

  -- Authoritative for ordering. A till can be offline for hours and flush later,
  -- so never sort this table by created_at.
  client_ts      TIMESTAMPTZ   NOT NULL,

  -- Idempotency: the POS re-sends until the server confirms.
  client_uid     VARCHAR(64)   NOT NULL,

  created_at     TIMESTAMPTZ   DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_creditmov_uid
  ON credit_movements(restaurant_id, client_uid);

CREATE INDEX IF NOT EXISTS idx_creditmov_client
  ON credit_movements(restaurant_id, client_key, client_ts DESC);

CREATE INDEX IF NOT EXISTS idx_creditmov_recent
  ON credit_movements(restaurant_id, client_ts DESC);


-- ═══════════════════════════════════════════════════
-- VIEW: balance derived from the movements, next to the balance the till
-- reported. `drift` should always be 0; anything else means the till's cache and
-- its own history disagree, which is worth a look.
-- ═══════════════════════════════════════════════════
CREATE OR REPLACE VIEW credit_reconciliation AS
SELECT
  c.restaurant_id,
  c.client_key,
  c.name,
  c.phone,
  c.balance                                             AS balance_pos,
  COALESCE(m.derived, 0)                                AS balance_derived,
  c.balance - COALESCE(m.derived, 0)                    AS drift,
  COALESCE(m.nb_credits, 0)                             AS nb_credits,
  COALESCE(m.nb_payments, 0)                            AS nb_payments,
  COALESCE(m.total_credit, 0)                           AS total_pris,
  COALESCE(m.total_paid, 0)                             AS total_regle,
  m.last_movement_at,
  c.archived
FROM credits c
LEFT JOIN (
  SELECT restaurant_id,
         client_key,
         SUM(delta)                                              AS derived,
         COUNT(*) FILTER (WHERE kind = 'credit')::int             AS nb_credits,
         COUNT(*) FILTER (WHERE kind = 'payment')::int            AS nb_payments,
         COALESCE(SUM(delta) FILTER (WHERE delta > 0), 0)         AS total_credit,
         COALESCE(SUM(-delta) FILTER (WHERE delta < 0), 0)        AS total_paid,
         MAX(client_ts)                                           AS last_movement_at
  FROM credit_movements
  GROUP BY restaurant_id, client_key
) m ON m.restaurant_id = c.restaurant_id AND m.client_key = c.client_key;


-- ═══════════════════════════════════════════════════
-- Useful queries once data arrives:
--
--   -- Total receivable (créances) outstanding
--   SELECT COALESCE(SUM(balance),0) FROM credits
--   WHERE restaurant_id = ? AND archived = FALSE AND balance > 0;
--
--   -- Debts the till and its own history disagree about
--   SELECT * FROM credit_reconciliation
--   WHERE restaurant_id = ? AND ABS(drift) > 0.001;
--
--   -- Archived clients who still owed money when they were deleted
--   SELECT name, balance, archived_at FROM credits
--   WHERE restaurant_id = ? AND archived = TRUE AND balance > 0;
--
--   -- Oldest untouched debts (chase list)
--   SELECT r.name, r.balance_pos, r.last_movement_at
--   FROM credit_reconciliation r
--   WHERE r.restaurant_id = ? AND r.archived = FALSE AND r.balance_pos > 0
--   ORDER BY r.last_movement_at NULLS FIRST;
-- ═══════════════════════════════════════════════════
